got OverflowError: Overflow occurred in npy_datetimestruct_to_datetime at  Dataset 31, Series 3818
python test.py

Dataset 31, Series 3818
Traceback (most recent call last):
  File "timestamps.pyx", line 2476, in pandas._libs.tslibs.timestamps.Timestamp.replace
OverflowError: Overflow occurred in npy_datetimestruct_to_datetime

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/snape/projects/Benchmarking-Hyper-Parameter-Tuning-Methods-for-Time-Series-Forecasting/test.py", line 8, in <module>
    for series_df in series_df_generator:
  File "/home/snape/projects/Benchmarking-Hyper-Parameter-Tuning-Methods-for-Time-Series-Forecasting/utils.py", line 77, in prepare_time_series
    values, index=pd.date_range(
  File "/home/snape/miniconda3/envs/mlenv/lib/python3.10/site-packages/pandas/core/indexes/datetimes.py", line 1008, in date_range
    dtarr = DatetimeArray._generate_range(
  File "/home/snape/miniconda3/envs/mlenv/lib/python3.10/site-packages/pandas/core/arrays/datetimes.py", line 468, in _generate_range
    i8values = np.array([x._value for x in xdr], dtype=np.int64)
  File "/home/snape/miniconda3/envs/mlenv/lib/python3.10/site-packages/pandas/core/arrays/datetimes.py", line 468, in <listcomp>
    i8values = np.array([x._value for x in xdr], dtype=np.int64)
  File "/home/snape/miniconda3/envs/mlenv/lib/python3.10/site-packages/pandas/core/arrays/datetimes.py", line 2780, in _generate_range
    end = start + (periods - 1) * offset  # type: ignore[operator]
  File "offsets.pyx", line 468, in pandas._libs.tslibs.offsets.BaseOffset.__radd__
  File "offsets.pyx", line 463, in pandas._libs.tslibs.offsets.BaseOffset.__add__
  File "offsets.pyx", line 141, in pandas._libs.tslibs.offsets.apply_wraps.wrapper
  File "offsets.pyx", line 2478, in pandas._libs.tslibs.offsets.YearOffset._apply
  File "offsets.pyx", line 5226, in pandas._libs.tslibs.offsets.shift_month
  File "timestamps.pyx", line 2479, in pandas._libs.tslibs.timestamps.Timestamp.replace
pandas._libs.tslibs.np_datetime.OutOfBoundsDatetime: Out of bounds timestamp: 2384-12-31 12:00:00 with frequency 'ns'